CREATE TABLE EMPLOYEE(
ID INT,
NAME VARCHAR(20) ,
ADDRESS VARCHAR(50),
PRIMARY KEY(ID)
);

INSERT INTO EMPLOYEE(ID,NAME,ADDRESS) VALUES (1,'ATUL','DELHI');
INSERT INTO EMPLOYEE(ID,NAME,ADDRESS) VALUES (2,'RAHUL','JAMMU');
INSERT INTO EMPLOYEE(ID,NAME,ADDRESS) VALUES (3,'MUNNA','CHAPRA');
INSERT INTO EMPLOYEE(ID,NAME,ADDRESS) VALUES (4,'RAJ','BIHAR');
INSERT INTO EMPLOYEE(ID,NAME,ADDRESS) VALUES (5,'BACCHA','KOLKATA');
INSERT INTO EMPLOYEE(ID,NAME,ADDRESS) VALUES (6,'KHUSI','PUNE');
INSERT INTO EMPLOYEE(ID,NAME,ADDRESS) VALUES (7,'AWADH','MUMBAI');
INSERT INTO EMPLOYEE(ID,NAME,ADDRESS) VALUES (8,'RAM','PATNA');
INSERT INTO EMPLOYEE(ID,NAME,ADDRESS) VALUES (9,'SHYAM','HAJIPUR');
INSERT INTO EMPLOYEE(ID,NAME,ADDRESS) VALUES (10,'SINGH','SONAR');